insert into public.series_carga (
  nombre_entidad,
  sobrescribir,
  posicion,
  codigo_serie,
  titulo_serie,
  categoria,
  unidad_gestora,
  libro_oficial,
  nivel_seguridad,
  advertencia_seguridad,
  sensibilidad_datos_personales,
  nivel_confidencialidad,
  tipo_acceso,
  condiciones_reutilizacion,
  codigo_causa_limitacion,
  normativa,
  valor_primario,
  plazo,
  valor_secundario,
  dictamen,
  documento_esencial,
  accion_dictaminada,
  ejecucion,
  motivacion
)
values
  (
    'Entidad demo',
    'no',
    '1',
    'SER-001',
    'Serie base',
    'General',
    'Unidad A',
    'Sí',
    'Bajo',
    'Sin advertencias',
    'No',
    'Público',
    'Libre',
    'Sin restricciones',
    'N/A',
    'Normativa demo',
    'Administrativo',
    '5 años',
    'Histórico',
    'Favorable',
    'Sí',
    'Conservación',
    'Automática',
    'Motivación de ejemplo'
  ),
  (
    'Entidad demo',
    'sí',
    '2',
    'SER-002',
    'Serie secundaria',
    'Especial',
    'Unidad B',
    'No',
    'Medio',
    'Revisar acceso',
    'Sí',
    'Restringido',
    'Parcial',
    'Con condiciones',
    'CL-01',
    'Normativa interna',
    'Legal',
    '10 años',
    'Cultural',
    'Condicionado',
    'No',
    'Transferencia',
    'Manual',
    'Motivación secundaria'
  );

insert into public.series_vinculacion (
  nombre_entidad,
  sobrescribir,
  cod,
  actividad,
  plazos
)
values
  ('Entidad demo', 'no', 'SER-001', 'Actividad demo', '5 años'),
  ('Entidad demo', 'sí', 'SER-002', 'Actividad secundaria', '10 años');
